### ISSUE TITLE
Coexist with other network login helpers

### ISSUE THREAD

**Issue by DMorgado** [rsalvaterra/Fon#3]
Hello, 

It would be nice that the Fon app played nice with other connection managers like PT WIFI / MEO WIFI.

The current behaviour is to delete all Fon networks from the connection manager and then manage the Fon networks it self. 

If auto connect is disabled the Fon app should not delete those SSIDs and let the native android connection manager take care of connection to a Fon network if it knows about it. A better way would be a dedicated option to disable the "delete".

Thanks ;-)

**Comment by alanthehat** [comment]
I have not noticed this behaviour from the other client that i use that is derived from the same source. I have used it in conjunction with several BT clients of different generations. 
Indeed, when it is struggling I use Android's connection manager to get it started.
However, since there are several million BT routers with the same SSID I quite often clear them out myself anyway. There seems to be no advantage in leaving open networks listed in Connection Manager, it even seems slower if there are BT or FON SSIDs listed that aren't currently visible
I am using https://github.com/gjedeer/androidwisprclient

**Comment by rsalvaterra-zz** [comment]
It should now play better with other captive portal open networks, passively connecting when autoconnect is disabled, and keeping the network configurations stored when disconnecting (bear in mind that you have to manually connect to supported SSIDs for the first time).
